FROM linuxmintd/mint19-amd64

RUN apt-get update -y && apt-get install -y curl sudo && apt-get install -y apt-transport-https && apt-get install python-gi

RUN wget -qO- https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -

RUN wget -qO- https://packages.microsoft.com/config/ubuntu/16.04/mssql-server-preview.list | tee /etc/apt/sources.list.d/mssql-server.list

RUN apt-get update -y

RUN apt-get install -y mssql-server

RUN sudo /opt/mssql/bin/mssql-conf set sqlagent.enabled true 

CMD /opt/mssql/bin/sqlservr