FROM centos

RUN yum update -y && yum install -y curl sudo

RUN sudo curl -o /etc/yum.repos.d/mssql-server.repo https://packages.microsoft.com/config/rhel/7/mssql-server-2017.repo

RUN yum install -y mssql-server

CMD /opt/mssql/bin/sqlservr