FROM opensuse/tumbleweed:latest

# download repo config file
RUN zypper addrepo -fc https://packages.microsoft.com/config/sles/12/mssql-server-preview.repo

# refresh repos
RUN zypper --gpg-auto-import-keys refresh

# install sql server
RUN zypper install -y mssql-server

# start sql server 
CMD /opt/mssql/bin/sqlservr