# building from ubuntu
FROM ubuntu:16.04

RUN apt-get update -y && apt-get install -y curl sudo && apt-get install -y apt-transport-https && apt-get install -y wget

# Import the public repository GPG keys
RUN wget -qO- https://packages.microsoft.com/keys/microsoft.asc | apt-key add -

# Register the Microsoft Ubuntu repository
RUN curl -o /etc/apt/sources.list.d/microsoft.list https://packages.microsoft.com/config/ubuntu/16.04/prod.list

# Update the list of products
RUN apt-get update

# Install mssql-cli
RUN apt-get install -y mssql-cli

